CREATE USER "nestjs" WITH ENCRYPTED PASSWORD '12345678';
ALTER ROLE "nestjs" SUPERUSER;

CREATE DATABASE "nestjs_app" OWNER "nestjs";

GRANT ALL PRIVILEGES ON DATABASE "nestjs_app" TO "nestjs";
GRANT ALL PRIVILEGES ON DATABASE "nestjs_app" TO "postgres";
