apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: test-nestjs-app
type: Opaque
stringData:
  POSTGRES_USER: "nestjs"
  POSTGRES_PASSWORD: "nestjspassword"
  POSTGRES_DB: "postgres"
  POSTGRES_PORT: "5432"
