---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nestjs-apps-v0-0-1
  namespace: test-nestjs-app
  labels:
    app: test-nestjs-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-nestjs-apps
  template:
    metadata:
      labels:
        app: test-nestjs-apps
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 2000
      initContainers:
        # https://hub.docker.com/_/busybox
        - name: wait-for-db
          image: busybox:1.37
          command:
            ["sh", "-c", "until nc -z postgres-18 5432; do sleep 1; done"]
          env:
            - name: DB_HOST
              value: "postgres-18"
        - name: init-db
          image: local-registry/test-nestjs-app:v0.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              value: "postgres-18"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
          command: ["npm", "run", "migration:run:prod"]
      containers:
        - name: test-nestjs-app
          image: local-registry/test-nestjs-app:v0.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8080"
            - name: DB_HOST
              value: "postgres-18"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
              ephemeral-storage: "126Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
              ephemeral-storage: "512Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp

      volumes:
        - name: tmp-volume
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-18
  namespace: test-nestjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-18
  template:
    metadata:
      labels:
        app: postgres-18
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 2000
      containers:
        - name: postgres
          image: postgres:18
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: "1000m"
              memory: "1Gi"
              ephemeral-storage: "512Mi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
              ephemeral-storage: "1Gi"
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "nestjs"]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "nestjs"]
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: test-nestjs-app-pvc
---

