---
apiVersion: v1
kind: Service
metadata:
  name: test-nestjs-apps-v0-0-1
  namespace: test-nestjs-app
spec:
  selector:
    app: test-nestjs-apps
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-18
  namespace: test-nestjs-app
spec:
  selector:
    app: postgres-18
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---

