version: '3'

services:
  hacken-io-db:
    container_name: hacken_io_db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "admin"
    ports:
      - "15432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    network_mode: local_default

  hacken-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "2000"
    networks:
      - hacken-network

  hacken-apache-kafka:
    image: confluentinc/cp-kafka:latest
    container_name: hacken_apache_kafka
    depends_on:
      - hacken-zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: "1"
      KAFKA_ZOOKEEPER_CONNECT: "hacken-zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_LOG_RETENTION_MS: '300000'
    networks:
      - hacken-network

networks:
  hacken-network: