apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  user: {{ .Values.mongodb.auth.rootUser | b64enc | quote }}
  password: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}