[package]
name = "snake"
version = "0.0.1"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [dependencies]
# libc = "0.2.144"
# rand = "0.8.5"

[profile.release]
opt-level = 3