spring:
  banner.image.location: "classpath:banner.txt"
  mustache:
    suffix: .html
    check-template-location: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: jdbc:h2:file:./ontu_admin
    username: ontu_bot
    password: pAsSwOrD
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

server:
  security:
    initialization-vector: oPw_1Ksny9eU_2sj # length = 16
    admin-secret-key: fioehrid_jeifg3_3049Jsdkewo
  cors: http://localhost:4200
  port: 8888

security:
  basic:
    enabled: false

telegram-bot-api:
  url: null

telegram-bot:
  directory: './resources/tg bot'
  env-file: .env
  advertisement-email-address: 
  
mail:
  host: 
  port: 
  application-email: 
  application-email-password: 
